const resourceConfig = {
  employees: {
    modelName: "Employees",
    primaryKey: "idEmployee",
    softDelete: true,
    defaultOrder: [["fullName", "ASC"]],
    editableFields: [
      "fullName",
      "shortName",
      "document",
      "rg",
      "zipCode",
      "street",
      "number",
      "complement",
      "neighborhood",
      "city",
      "state",
      "primaryPhone",
      "secondaryPhone",
      "nameSecPhone",
      "email",
      "comment",
      "birthDate",
      "roleId",
      "bankData",
      "active",
    ],
  },
  suppliers: {
    modelName: "Suppliers",
    primaryKey: "idSupplier",
    defaultOrder: [["tradeName", "ASC"], ["fullName", "ASC"]],
    editableFields: [
      "fullName",
      "tradeName",
      "contactName",
      "document",
      "rg",
      "street",
      "neighborhood",
      "city",
      "state",
      "zipCode",
      "phoneCommercial1",
      "phoneCommercial2",
      "fax",
      "phoneMobile",
      "email",
      "comment",
      "active",
      "blocked",
    ],
  },
  roles: {
    modelName: "Roles",
    primaryKey: "id",
    defaultOrder: [["desc", "ASC"]],
    editableFields: ["desc"],
  },
  colors: {
    modelName: "Colors",
    primaryKey: "id",
    defaultOrder: [["desc", "ASC"]],
    editableFields: ["desc"],
  },
  categories: {
    modelName: "Categories",
    primaryKey: "id",
    defaultOrder: [["id", "ASC"]],
    editableFields: ["desc"],
  },
  sizes: {
    modelName: "Sizes",
    primaryKey: "id",
    defaultOrder: [["desc", "ASC"]],
    editableFields: ["desc"],
  },
  "clothings-types": {
    modelName: "ClothingsType",
    primaryKey: "id",
    defaultOrder: [["desc", "ASC"]],
    editableFields: ["desc"],
  },
  "products-types": {
    modelName: "ProductsTypes",
    primaryKey: "id",
    defaultOrder: [["desc", "ASC"]],
    editableFields: ["desc"],
  },
  fabrics: {
    modelName: "Fabrics",
    primaryKey: "id",
    defaultOrder: [["desc", "ASC"]],
    editableFields: ["desc"],
  },
  "payment-types": {
    modelName: "PaymentTypes",
    primaryKey: "idPaymentType",
    defaultOrder: [["idPaymentType", "ASC"]],
    editableFields: ["desc"],
  },
};

function getAdminResourceConfig(resource) {
  return resourceConfig[resource] || null;
}

module.exports = {
  getAdminResourceConfig,
};
